#if DESKBOX_NATIVE_AOT
namespace DeskBox.ViewModels;

[WinRT.GeneratedBindableCustomProperty([
    nameof(AppVersion),
    nameof(AutoCheckForUpdates),
    nameof(AutoStart),
    nameof(AutoStartStatusText),
    nameof(AutoStartStatusVisibility),
    nameof(AutoStartSystemSettingsVisibility),
    nameof(AutoStartModeVisibility),
    nameof(SelectedAutoStartMode),
    nameof(AvailableAutoStartModeOptions),
    nameof(AvailableAttachmentStorageModeOptions),
    nameof(AvailableHiddenCacheCleanupDelayOptions),
    nameof(AvailableHiddenCacheCleanupScopeOptions),
    nameof(AvailablePerformanceCacheBudgetOptions),
    nameof(AvailableVisibleIdleCacheCleanupDelayOptions),
    nameof(AvailableLanguageOptions),
    nameof(AvailablePerformanceModeOptions),
    nameof(CanOpenUpdateFallback),
    nameof(ContinuousDecorativeAnimationsSummaryText),
    nameof(CanViewReleaseNotes),
    nameof(DonationQrCodeVisibility),
    nameof(IsOneClickActionEnabled),
    nameof(ManualUpdateDownloadUrl),
    nameof(MicrosoftStoreLink),
    nameof(OfficialWebsiteLink),
    nameof(OneClickActionButtonText),
    nameof(ReleaseNotesButtonVisibility),
    nameof(SelectedAttachmentStorageMode),
    nameof(SelectedHiddenCacheCleanupDelaySeconds),
    nameof(SelectedHiddenCacheCleanupScope),
    nameof(SelectedLanguage),
    nameof(SelectedPerformanceCacheBudget),
    nameof(SelectedPerformanceMode),
    nameof(SelectedVisibleIdleCacheCleanupDelaySeconds),
    nameof(IdleWorkingSetTrimEnabled),
    nameof(ImmediateHiddenWorkingSetTrimEnabled),
    nameof(QuiescenceWorkingSetTrimEnabled),
    nameof(StoreSupportCardVisibility),
    nameof(UpdateAutoCheckVisibility),
    nameof(UpdateDetailText),
    nameof(UpdateFallbackActionText),
    nameof(UpdateFallbackVisibility),
    nameof(UpdateProgressIsIndeterminate),
    nameof(UpdateProgressText),
    nameof(UpdateProgressValue),
    nameof(UpdateProgressVisibility),
    nameof(UpdateStatusText),
    nameof(UpdateSummaryText),
    nameof(UpdateSummaryVisibility),
    nameof(ViewReleaseNotesButtonText),
], [])]
public partial class SettingsViewModel
{
}
#endif
